services:
  db:
    image: mysql:8.0
    container_name: Tuan01_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    container_name: lab_node
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: shopdb
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata:
